### ISSUE TITLE
Sample project error

### ISSUE THREAD

**Issue by annjawn** [andreamazz/SubtleVolume#18]
The sample project is giving this error when I tap the volume + button.

`Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: SubtleVolume.SubtleVolumeError.unableToChangeVolumeLevel`

And this is where it fails-

```
@IBAction func plusAction() {
    try! volume.setVolumeLevel(volume.volumeLevel + 0.05, animated: true)
  }
```

**Comment by andreamazz** [comment]
Are you running on the simulator? It doesn't work there, you need a device.

**Comment by annjawn** [comment]
@andreamazz didn't realize that was the requirement. I'll give it a try. thanks.
