### ISSUE TITLE
Not showing after webkit view played

### ISSUE THREAD

**Issue by PietroMessineo** [andreamazz/SubtleVolume#25]
Hi guys,

After few tried I understood that SubtleVolume is not working if a video has been played through the WebKit view (WKWebView). 

So, for reproduce the issue, load a web page (YouTube), try to increase or decrease the volume (everything is working for what about the SubtleVolume) then play a video, come back and no custom controls anymore.

**Comment by andreamazz** [comment]
Ciao Pietro,
did you try calling `resume` after the webkit video played?

**Comment by PietroMessineo** [comment]
Ciao Andrea,

Calling resume everything is working perfectly :D

I’ll let you know if there will be other cases in which it will not be displayed, thank you so much!

--
Best regards,
Pietro Messineo


On 5 aprile 2019 a 16:34:04, Andrea Mazzini (notifications@github.com<mailto:notifications@github.com>) scritto:

Ciao Pietro,
did you try calling resume after the webkit video played?
