### ISSUE TITLE
Typo in method name. increseVolume -> increaseVolume

### ISSUE THREAD

**Issue by jwandrews** [andreamazz/SubtleVolume#26]
Found a typo in method name: https://github.com/andreamazz/SubtleVolume/blob/9a6814265d13cfe50771212be5f984b07b95c07a/Source/SubtleVolume.swift#L170

I guess this would be a breaking change since it’s changing public API.

**Comment by andreamazz** [comment]
Yep, I noticed a while ago, cried about it a little bit, and hoped that no one would notice. 

😬 

I'll fix it and release a new minor.

**Comment by andreamazz** [comment]
Done, released 1.1.0

**Comment by jwandrews** [comment]
wonderful! keep up the good work
