### ISSUE TITLE
Not removing self as an observer

### ISSUE THREAD

**Issue by gapl** [andreamazz/SubtleVolume#6]
Basically what it says in the title. Would gladly open a pull request when I have 15 min to breathe :) Otherwise this is the snippet:

```
deinit {
    AVAudioSession.sharedInstance().removeObserver(self, forKeyPath: "outputVolume", context: nil)
}
```

**Comment by andreamazz** [comment]
Hi @gapl 
My bad! I'll push a fixed version right away. Thanks for the heads up 👍
