### ISSUE TITLE
SubtleVolume Objective-C

### ISSUE THREAD

**Issue by SvenTiigi** [andreamazz/SubtleVolume#7]
Hi there,

I converted your amazing SubtleVolume Project :+1:  to Objective-C and also made it available through CocoaPod (https://github.com/SvenTiigi/STSubtleVolumeC)

I've used some of your graphics in the readme file. I hope it's okay. If you wish to remove some of the graphics from the readme file just open a issue like I do :)

Great Work!

**Comment by andreamazz** [comment]
Hi @SvenTiigi 

Sure, no problem.  

I'll be honest... I don't really get the need to translate a lib between two language that interoperate with (mostly) no issues, but ¯\_(ツ)_/¯ 

Cheers 🍻
